- .github/ISSUE_TEMPLATE/bug-report---.md
- .github/ISSUE_TEMPLATE/feature-request---.md
- .github/ISSUE_TEMPLATE/general-question-feedback----.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/policies/resource-management.yml
> GitHub Configurations

- src/modules/WARA/advisor/advisor.psm1
- src/tests/advisor/advisor.tests.ps1
- src/tests/data/newAdvisorData.json
1. _Replace me_
2. _Replace me_
> Advisor Module

- docs/advisor/Get-WAFAdvisorRecommendations.md
- docs/collector/Get-WAFAllAzGraphResource.md
- docs/collector/Get-WAFResourceGroup.md
- docs/collector/Get-WAFResourceType.md
- docs/collector/Get-WAFTaggedRGResources.md
- docs/collector/Get-WAFTaggedResources.md
- docs/collector/Invoke-WAFQueryLoop.md
- docs/outage/Get-WAFOutage.md
- docs/utils/Connect-WAFAzure.md
- docs/utils/Test-ResourceGroupId.md
- docs/utils/Test-ScriptParameters.md
- docs/utils/Test-SubscriptionId.md
- docs/utils/Test-TagPattern.md
- src/tests/data/outage/restApiMultipleResponseData.json
- src/tests/data/outage/restApiSingleResponseData.json
- src/tests/data/retirement/restApiMultipleResponseData.json
- src/tests/data/retirement/restApiSingleResponseData.json
Fix the subscription ID in the test data.
- None
- None
> Fix: Fix subscription ID in test data

- docs/support/Get-WAFSupportTicket.md
- docs/support/New-WAFSupportTicketObject.md
- src/modules/wara/support/support.psm1
- src/tests/data/support/argQueryMultipleResultData.json
- src/tests/data/support/argQuerySingleResultData.json
- src/tests/support/support.tests.ps1
Added an implementation and tests for the support.psm1 module.
- AB#36897
- AB#36898
- AB#36899
- None
> feat: Add support.psm1

- docs/support/Get-WAFSupportTicket.md
- docs/support/New-WAFSupportTicketObject.md
- docs/support/support.md
- src/modules/wara/outage/outage.psm1
- src/modules/wara/retirement/retirement.psm1
- src/modules/wara/support/support.psm1
Update command-based help.
- None
- None
> feat: Update command-based help

- docs/advisor/advisor.md
- docs/utils/Test-ResourceGroupId.md
- docs/utils/Test-ScriptParameters.md
- src/modules/wara/support/support.psm1
- src/tests/support/support.tests.ps1
- Explicitly import dependent module.
- Tune ARG query.
- Change code formatting.
- None
- None
> refactor: Tune ARG query in Support module

- docs/advisor/advisor.md
- docs/collector/collector.md
- docs/outage/outage.md
- docs/retirement/retirement.md
- docs/servicehealth/servicehealth.md
- docs/support/support.md
- docs/utils/utils.md
- src/tests/outage/outage.tests.ps1
- src/tests/retirement/retirement.tests.ps1
Fix tests for outage and retirement.
- None
- None
> fix: Fix tests for outage and retirement

- docs/advisor/Get-WAFAdvisorRecommendation.md
- docs/advisor/advisor.md
- docs/collector/Get-WAFTaggedResource.md
- docs/collector/Get-WAFTaggedResourceGroup.md
- docs/collector/collector.md
- src/modules/wara/outage/outage.psm1
Refactor the Outage module.
- Use the util module's function to validate GUID.
- Fix code formatting.
- Fix comments.
- None
- None
> refactor: Outage module

- docs/advisor/advisor.md
- docs/collector/collector.md
- src/modules/wara/outage/outage.psm1
Fix a typo in a comment.
- None
- None
> fix: Fix typo in comment

- src/modules/wara/retirement/retirement.psm1
Refactor the Retirement module.
- Use the util module's function to validate GUID.
- Fix code formatting.
- Fix comments.
- None
- None
> refactor: Retirement module

- src/modules/wara/support/support.psm1
Refactor the Support module.
- Use the util module's function to validate GUID.
- Fix comment-based help
- None
- None
> refactor: Support module

- src/modules/wara/advisor/advisor.psd1
- src/modules/wara/advisor/advisor.psm1
- src/modules/wara/collector/collector.psd1
- src/modules/wara/collector/collector.psm1
- src/modules/wara/outage/outage.psd1
- src/modules/wara/retirement/retirement.psd1
- src/modules/wara/runbook/runbook.psd1
- src/modules/wara/runbook/runbook.psm1
- src/modules/wara/scope/scope.psd1
- src/modules/wara/scope/scope.psm1
- src/modules/wara/servicehealth/servicehealth.psd1
- src/modules/wara/servicehealth/servicehealth.psm1
- src/modules/wara/support/support.psd1
- src/modules/wara/utils/utils.psd1
- src/modules/wara/utils/utils.psm1
- src/modules/wara/wara.psd1
- src/modules/wara/wara.psm1
- src/tests/advisor/advisor.tests.ps1
- src/tests/collector/collector.tests.ps1
- src/tests/outage/outage.tests.ps1
- src/tests/retirement/retirement.tests.ps1
- src/tests/scope/scope.tests.ps1
- src/tests/servicehealth/servicehealth.tests.ps1
- src/tests/support/support.tests.ps1
- src/tests/utils/utils.tests.ps1
- Change the code formatting based on common style.
- Use four whitespaces for indents.
- Use the VS Code default formatter for PowerShell.
- There are no functional changes in this pull request.
- None
- None
> style: Change code formatting based on common style

- docs/collector/Invoke-WAFQueryLoop.md
- src/modules/wara/collector/collector.psm1
- src/modules/wara/wara.psm1
Added support for specialized workloads AVD/AVS/SAP/HPC
> add: specialized workloads

- src/modules/wara/scope/scope.psm1
Fix the data type of the return value to always an array even if the return array has only a single element.
- #57 
- None
> fix: Fix data type of return value to always an array

- src/modules/wara/scope/scope.psm1
Format indents and code style.
- None
- None
> style: Code formatting

- src/modules/wara/wara.psm1
Fix issue #65 
- Fixes #65 
- None
> fix: Fix issue 65

- src/modules/wara/advisor/advisor.psm1
Added and updated comment based help for the Advisor.psm1 module.
> docs: updated advisor comment based help.

- src/modules/wara/servicehealth/servicehealth.psm1
Updated documentation for Service Health
> Update service health docs

- .github/workflows/pestertests.yml
> update pester pipeline

- .editorconfig
- src/modules/wara/wara.psm1
- Change code formatting
- Add editorconfig
None
- None
> style: Small changes

- src/modules/wara/wara.psm1
Change code formatting.
None
- None
> style: Change code formatting

- src/modules/wara/wara.psd1
- src/modules/wara/wara.psm1
Updated for changes to the specialized workloads. Now uses the "tags" property on the recommendation to identify specialized recommendations.
> update: specialized workloads

- README.md
Add a link to the PowerShell installation document.
None
None
> feat: Add link to PowerShell document

- src/modules/wara/advisor/advisor.psd1
- src/modules/wara/analyzer/analyzer.psd1
- src/modules/wara/collector/collector.psd1
- src/modules/wara/outage/outage.psd1
- src/modules/wara/reports/reports.psd1
- src/modules/wara/retirement/retirement.psd1
- src/modules/wara/runbook/runbook.psd1
- src/modules/wara/scope/scope.psd1
- src/modules/wara/servicehealth/servicehealth.psd1
- src/modules/wara/support/support.psd1
- src/modules/wara/utils/utils.psd1
- src/modules/wara/wara.psd1
Specify CompatiblePSEditions to Core.
None
None
> fest: Specify CompatiblePSEditions to Core

- src/modules/wara/analyzer/2_wara_data_analyzer.ps1
- src/modules/wara/analyzer/analyzer.psm1
1. _Replace me_
2. _Replace me_
> Recommendations.json

- src/modules/wara/wara.psd1
- Fixes issue with Start-WARAReport not running due to empty rows in the excel file.
- Applies data validation to 4.ImpactedResourcesAnalysis worksheet for 'REQUIRED ACTIONS / REVIEW STATUS' column.
- Data validation rule is set to error if cell contents are not equal to Reviewed or Pending. This ensures that there are no entry issues with the excel column.
#89
> alpha release: 0.0.16

- docs/outage/Get-WAFOutage.md
- docs/outage/New-WAFOutageObject.md
- docs/outage/outage.md
- docs/retirement/Get-WAFResourceRetirement.md
- docs/retirement/New-WAFResourceRetirementObject.md
- docs/retirement/retirement.md
- docs/support/Get-WAFSupportTicket.md
- docs/support/New-WAFSupportTicketObject.md
- docs/support/support.md
- docs/utils/Get-AzureRestMethodUriPath.md
- docs/utils/Invoke-AzureRestApi.md
- docs/wara/Start-WARAAnalyzer.md
- docs/wara/Start-WARACollector.md
- docs/wara/configfile.example
Update documents.
- None
- None
> docs: Update doc

- src/modules/wara/analyzer/analyzer.psm1
- src/modules/wara/reports/reports.psm1
- src/modules/wara/wara.psm1
- Improves the module version check message.
- Changes code formatting style for consistency.
- None
- None
> feat: Improve module version check message

- docs/wara/configfile.example
Testing teams integration with GitHub.
None
None
> test: teams integration

- src/modules/wara/analyzer/2_wara_data_analyzer.ps1
Adds an Excel formula to automatically calculate the number of resources (column C) in the Expert-Analysis file (3.AnalysisPlanning worksheet)
ADO Task 39512
> fix / WARA - Update 3.AnalysisPlanning worksheet

- src/modules/wara/wara.psd1
> Release v1.0.1

- src/modules/wara/reports/3_wara_reports_generator.ps1
Just a small fix to remove the commented lines of the PPT functions
ADO Issue 39902
> Fix/Removed comments on the PPT functions

- README.md
- src/modules/wara/wara.psd1
- Fixed required actions message on Expert-Analysis
- Fixed advisorResourceObj issues
- Fixed the architectural recommendation on the Expert-Analysis spreadsheet
- Fixed the resource counts in the Analysis Planning worksheet in Expert-Analysis
- Fixed Resource Type is not available in either APRL or Advisor so that these now show up correctly in the Expert-Analysis spreadsheet
- Added chart code for Assessment Findings
- Updated Assessment findings Pie Charts to display percentage correctly
- Updated Assessment finding to use textboxes instead of columns for resource counts
- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull …
> Release v1.0.2

- README.md
Adds a CSV file to the flow diagram.
None
None
> docs: Add CSV file to flow diagram

- src/modules/wara/analyzer/2_wara_data_analyzer.ps1
- src/modules/wara/reports/3_wara_reports_generator.ps1
- src/modules/wara/wara.psd1
This PR updates the module version to v1.0.5.
> Release v1.0.5

- src/modules/wara/reports/3_wara_reports_generator.ps1
This PR updates the pptx template and also fix the Outages section to prevent empty slides.
ADO #40186
> Update pptx template

- src/modules/wara/reports/3_wara_reports_generator.ps1
Resolve the specified relative path to an absolute path before using it to fix the PPT template relative path issue.
Issue: The PowerPoint process cannot find the template file if specify a relative path to the PPTTemplateFile parameter because the  PowerShell script and the PowerPoint process have different current directory.
None
None
> fix: Fix PPT template relative path issue

- src/modules/wara/reports/3_wara_reports_generator.ps1
Refactors the Office process stop handling.
None
None
> refactor: Refactor Office process stop handling
