src/modules/wara/outage/outage.psm1

Fix comment-based help.
- None
- None

fix: Comment-based help

---

docs/advisor/Test-WAFIsGuid.md
docs/collector/Test-WAFIsGuid.md
docs/outage/Test-WAFIsGuid.md
docs/retirement/Test-WAFIsGuid.md
docs/servicehealth/Test-WAFIsGuid.md
docs/support/Test-WAFIsGuid.md
docs/utils/Test-WAFIsGuid.md
src/modules/wara/utils/utils.psm1

- Specify data type to a parameter of Test-WAFIsGuid.
- Fix comment-based help for Invoke-AzureRestApi and Get-AzureRestMethodUriPath.
- Use the util module's function to validate GUID for Invoke-AzureRestApi and Get-AzureRestMethodUriPath.
- Fix indentation for Invoke-AzureRestApi.
- None
- None

fix: Util module

---

src/modules/wara/advisor/advisor.psd1
src/modules/wara/collector/collector.psd1
src/modules/wara/outage/outage.psd1
src/modules/wara/retirement/retirement.psd1
src/modules/wara/runbook/runbook.psd1
src/modules/wara/scope/scope.psd1
src/modules/wara/servicehealth/servicehealth.psd1
src/modules/wara/support/support.psd1
src/modules/wara/wara.psd1

- Added a requirement for the minimum version of dependent PowerShell modules from the Az PowerShell module.
- Added the minimum Microsoft-supported PowerShell version 7.4.0.
- Removed required modules and PowerShell version checks from the *nested* modules to increase maintainability.
None
None

fix: add dependent modules version + add required powershell version

---

src/modules/wara/utils/utils.psd1
src/modules/wara/wara.psd1

Change module dependencies to clean.
After merging this PR:
- None
- None

feat: Change module dependencies to clean

---

src/modules/wara/wara.psm1

Change the parameter name for recommendation data URI.
- None
- None

feat: Change parameter name for recommendation data URI

---

src/modules/wara/utils/utils.psm1
src/tests/utils/utils.tests.ps1

Fix the connect to Azure tenant issue when the current tenant is different with specified by the TenantID parameter. Also, update tests for Connect-WAFAzure.
Repro steps:
1. The current context is for **Tenant A**.
2. Run Start-WARACollector with **Tenant B** as the TenantID parameter.
3. It doesn't run correctly.
- None
- None

fix: Connect to Azure tenant issue when the current tenant is different with specified

---

src/modules/wara/utils/utils.psm1

Fix the return value to always as an array.
Invoke-WAFQuery returns $null if the return value is an empty array (= there are no query result). For fix this, added a comma (array operator). Then the return value is always as an array.
- None
- None

Fix return value to always as array

---

src/modules/wara/utils/utils.psm1

Revert the PR #46 change.
- None
- None

revert: Revert PR #46 change

---

src/modules/wara/collector/collector.psm1
src/modules/wara/utils/utils.psm1

Fix the return value of Invoke-WAFQuery function.
Invoke-WAFQuery returns $null if there are no query result. For fix this, added a comma (use array operator). Then the return value is always as an array. The function returns an empty array if there are no query result.
- None
- None

fix: Fix return value of Invoke-WAFQuery

---

src/modules/wara/utils/utils.psm1

Suppress the output of Connect-AzAccount.
Connect-AzAccount returns the tenant and subscription information that switch to. This PR fixed (suppressed) it.
- None
- None

fix: Suppress output of Connect-AzAccount

---

src/modules/wara/collector/collector.psm1
src/modules/wara/wara.psm1

Resolve issue with subscriptionid or resourcegroup not being present with -tenantid
closes #51

fix: Parameter validation

---

src/modules/wara/collector/collector.psm1

Fix issue #52
- Fix #52 
- None

fix: Fix issue #52

---

src/modules/wara/utils/utils.psm1

Fix a variable name typo.
- None
- None

fix: Fix variable name typo

---

src/modules/wara/wara.psm1

Adds the ScriptDetails object to the output JSON in the `Start-WARACollector` function in `src/modules/wara/wara.psm1`.
$ScriptDetails = [PSCustomObject]@{
Version = $(Get-Module -name $MyInvocation.MyCommand.ModuleName).Version
ElapsedTime = $StopWatch.Elapsed.toString("hh\:mm\:ss")
SAP = $SAP
AVD = $AVD
AVS = $AVS
HPC = $HPC
TenantId = $Scope_TenantId
SubscriptionIds = $Scope_SubscriptionIds
ResourceGroups = $Scope_ResourceGroups
ImplicitSubscriptionIds = $Scope_ImplicitSubscriptionIds
Tags = $Scope_Tags
AzureEnvironment = $AzureEnvironment
RecommendationDataUri = $RecommendationDataUri
RecommendationResourceTypesUri = $RecommendationResourceTypesUri
UseImplicitRunbookSelectors = $UseImplicitRunbookSelectors
RunbookFile = $RunbookFile
ConfigFile = $ConfigFile 
ConfigData = $ConfigData …

feat: scriptdetails object

---

src/modules/wara/wara.psm1

Fix the parameter name capitalization.
- None
- None

style: Parameter name capitalization

---

src/modules/wara/wara.psm1

Fix return data type as an array even if only a single element.
None
None

fix: Fix return data type as an array even if only a single element

---

src/modules/wara/wara.psd1

Add required modules for install those as dependency when install the wara module because Install-Module cmdlet installs dependency modules if those specified in the manifest file as RequiredModules.
None
None

feat: Add required modules to wara's manifest

---

src/modules/wara/reports/3_wara_reports_generator.ps1

This adds a check to reports generator to see if clipboard history is enabled. If it is, it throws an error. Clipboard history will break the PPT generation.

fix: add check for clipboard history

---

docs/wara/Start-WARAAnalyzer.md
src/modules/wara/analyzer/2_wara_data_analyzer.ps1
src/modules/wara/analyzer/analyzer.psm1

Change the parameter name for recommendations.json for consistency.
Start-WARACollector uses `RecommendationDataUri` for the parameter name to recommendations.json. But Start-WARAAnalyzer
uses `RecommendationsUrl` for it. This is inconsistency between cmdlets. We should use the same name for the same meaning parameters.
- None
- None

refactor: Change parameter name for recommendations.json to consistency

---

src/modules/wara/reports/3_wara_reports_generator.ps1

Changes the elapsed time measuring method from Measure-Command to Stopwatch in 3_wara_reports_generator.ps1. Because it is difficult to handle exceptions in the script block of Measure-Command.
- None
- None

refactor: Change Measure-Command to Stopwatch

---

src/modules/wara/wara.psm1
src/tests/wara/wara.tests.ps1

Fixes issue with specialized parameter sets not being supported with config files.
#95 
none

fix: parameter sets

---

src/modules/wara/analyzer/2_wara_data_analyzer.ps1

The WAF recommendations have wrong learn more links. This pull request fixes that.
**The wara module 1.0.2 (With wrong learn more links):**
All WAF recommendations have the same learn more link and its wrong link.
**The wara module 1.0.2 with this PR (With correct learn more links):**
- None
- None

fix: Fix WAF recommendation's learn more link

---

src/modules/wara/analyzer/2_wara_data_analyzer.ps1

Fixes issue with resources being filtered out of Expert-Analysis when the Advisory section in the JSON output is blank. This is an extreme edge case, but should be handled gracefully with this PR.
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x ] Ensured PR tests are passing
- [ x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x ] …

fix: advisor resource 0 handling

---

src/modules/wara/scope/scope.psm1

Fixes Get-WAFFilteredResourceList where the filtering would remove any resource resulting in a null output.

fix: get-waffilteredresourcelist handles 0 recommendations

---

src/modules/wara/wara.psm1

This PR changes the URL for the `RecommendationResourceTypesUri` parameter in the `Start-WARACollector` function in the `wara.psm1` file to point to the WARA-Build repository location.

update: Change WARAinScopeResourceTypes.csv url

---

src/modules/wara/reports/3_wara_reports_generator.ps1

Event if there are no support tickets in the Expert Analysis file a "template" slide will be present in the Executive Summary Presentation. This PR adds an "IF" statement to validate if there are support tickets in the Expert Analysis file, in case there are none, the template slide will be removed from the presentation. In case there are support tickets, the slide will be added to the presentation normally.
ADO 39924

Adding the IF statement to check if there are Support Tickets

---

README.md

Readme docs update with: Add warning for Start-WARAReport section in README to inform user that all instances of PowerPoint and Excel should be closed prior to running Start-WARAReport.
None

docs: Add warning for Start-WARAReport in README

---

src/modules/wara/utils/utils.psm1
src/modules/wara/wara.psm1

This PR addresses the issue with specifying Azure Environments. We have removed the validate list and have left the default value as `AzureCloud` for both `Connect-WAFAzure` and `Start-WARACollector` functions.
This means if you need to utilize a non-default Azure Environment, you can specify it without any restrictions.
#166 
None
- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is …

Remove validate set from scripts for azure environment

---

.github/PULL_REQUEST_TEMPLATE.md

Fixs repo related URLs in the pull request template.
None
None

fix: Fix repo related URLs in PR template

---

src/modules/wara/reports/3_wara_reports_generator.ps1

Adds better exception experience to Start-WARAReport by an exception handling that covering the entire script.
Changes:
- Sets the ErrorActionPreference to Stop.
- Adds a `trap` statement to catch exceptions over the entire script.
- Removes unnecessary exit statements after Write-Error.
- Refactor the parameter validation.
- Wrap the Office app part using the try-finally statement.
- AB#40801
None

feat: Add better exception experience to Start-WARAReport

---

src/modules/wara/analyzer/2_wara_data_analyzer.ps1
src/modules/wara/reports/3_wara_reports_generator.ps1

- Formatted the code of the Start-WARAReport using the [PowerShell extension (PSScriptAnalyzer)](https://code.visualstudio.com/docs/languages/powershell) provided code formatting (`Format Document` command).
- No code changes.
- [PSScriptAnalyzer integration](https://code.visualstudio.com/docs/languages/powershell#_psscriptanalyzer-integration)
> **PSScriptAnalyzer** also provides code formatting. You can invoke automatic document formatting with the **Format Document** command or the (`Shift+Alt+F`) keyboard shortcut.
None
None

style: Format Start-WARAReport code

---

src/modules/wara/analyzer/2_wara_data_analyzer.ps1

- Formatted the code of the Start-WARAAnalyzer using the [PowerShell extension (PSScriptAnalyzer)](https://code.visualstudio.com/docs/languages/powershell) provided code formatting (`Format Document` command).
- No code changes.
- [PSScriptAnalyzer integration](https://code.visualstudio.com/docs/languages/powershell#_psscriptanalyzer-integration)
> **PSScriptAnalyzer** also provides code formatting. You can invoke automatic document formatting with the **Format Document** command or the (`Shift+Alt+F`) keyboard shortcut.
None
None

style: Format Start-WARAAnalyzer code
